### ISSUE TITLE
Make development use mitmproxy Docker image

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#1002]
At the moment in development you use mitmproxy from the Procfile (if you uncomment it). This is not how production works so you can be fooled into thinking you've fixed something when you haven't: https://github.com/openaustralia/morph/issues/986#issuecomment-217338362

Development should be as close to production as possible so we should make development use the Docker mitmproxy.

**Comment by mlandauer** [comment]
It looks like the OS X support for setting up docker has moved on a million miles since I last used it. Might be worth revisiting moving more of the development setup over to using docker.

**Comment by mlandauer** [comment]
After taking a bit more of a look at things I don't think this is worth the effort right now. The problem before was caused by there being two copies of the `mitmproxy` directory in the repo, one which was used by mitmproxy started from the `Procfile` and one which was used by the docker images. This has been fixed. As I think this was the largest source of confusion I don't think it's necessary to move development over to using the docker image right now. If we do that it would make more sense to come up with an overall way of doing all development using docker images which is perfectly possible just a reasonable chunk of work, I think.
