### ISSUE TITLE
Cannot delete scraper due to foreign key constraint failing

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#1084]
```
[Morph/production] ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`morph`.`metrics`, CONSTRAINT `fk_rails_14230a8cc7` FOREIGN KEY (`run_id`) REFERENCES `runs` (`id`)): DELETE FROM `runs` WHERE `runs`.`id` = 168069
```
## Backtrace

```
line 133 of [PROJECT_ROOT]/app/controllers/scrapers_controller.rb: destroy
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/35868/faults/31032607)

**Comment by tmtmtmtm** [comment]
I've also noticed that I can't delete scrapers that have Webhooks defined. Once I delete those, I can then delete the scraper.

**Comment by equivalentideas** [comment]
I think the issue here might be that we're trying to delete the Run(s) associated with the scraper, but there are Metric(s) that reference those runs.

**Comment by equivalentideas** [comment]
I think the issue here might be that we're trying to delete the Run(s) associated with the scraper, but there are Metric(s) that reference those runs.

**Comment by chrismytton** [comment]
I've just been looking at this locally.

It seems that when a run has _multiple_ metrics associated with it, trying to destroy the run causes an error. This is because Run is supposed to `have_one` Metric, but this isn't being enforced at the database level, so there are certain runs that have more than one metric associated with them.

I've opened https://github.com/openaustralia/morph/pull/1145 with a failing test to demonstrate this problem.

**Comment by equivalentideas** [comment]
@chrismytton nice sloothing :)

> certain runs that have more than one metric associated with them

Any idea how a Run gets into this state?

**Comment by chrismytton** [comment]
> Any idea how a Run gets into this state?

Good question! I've just had a quick grep around and it looks like [these lines in `Morph::Runner`](https://github.com/openaustralia/morph/blob/b921061a680b71aafa2d911fa825819561cb8222/lib/morph/runner.rb#L147-L148), which create a metric for a run, are the primary suspect. Working back up the stack leads me to [this line in `RunWorker`](https://github.com/openaustralia/morph/blob/05b847940be48f43a20ca624051bc273e573836c/app/workers/run_worker.rb#L10), which finds a run and then passes it to `Morph::Worker`.

It seems that if a `RunWorker` job get retried by Sidekiq, it will use the existing run, but `Morph::Runner` will create a new `Metric` for that run on each retry.

So I think we probably want to do some kind of `find_or_create` type dance in `Morph::Runner` to check if a metric already exists for the run, and if it does then just update that rather than creating a new one?

**Comment by chrismytton** [comment]
I've opened a pull request that _should_ fix this issue: https://github.com/openaustralia/morph/pull/1145
