### ISSUE TITLE
node.js scrapers failing

### ISSUE THREAD

**Issue by atompkins** [openaustralia/morph#1275]
Hi

I have multiple node.js scrapers failing with
`Error: Invalid semantic version "16.x"`
This has been happening for 13 days now.
At first it said `Error: Invalid semantic version "14.x"`
I changed it to 16.x to see if maybe support for 14.x had been dropped.
Other than that these scrapers haven't been changed since January and had been running fine.
I checked the Heroku knowledge base, both 14.x and 16.x are supported.

Any ideas? thanks

**Comment by daald-docker** [comment]
mine also. I didn't have any declaration in my package.json, so it took "6.x" as default but was not happy with this choice :stuck_out_tongue:

**Comment by daald-docker** [comment]
It seems that **all** nodejs scrapers are failing since probably 1st Oct, as if there are no nodejs versions available anymore. not the default version, not any of the explicit versions which I tried, and not the versions which are mentioned on examples.

I posted some more details on https://help.morph.io/t/node-js-scrapers-failing/617/2

**Comment by Taz17** [comment]
@mlandauer this issue points towards a bigger issue on morph for nodejs scrapers.

**Comment by mlandauer** [comment]
Fixed by https://github.com/openaustralia/buildstep/commit/1033f663bff788978e144fae3bbbda058b059b3f
