### ISSUE TITLE
Make data table more flexible

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#356]
Looks like https://github.com/filamentgroup/tablesaw might be useful for this

**Comment by equivalentideas** [comment]
There are a few different elements to this. We want to make the tables layout flexible because currently it is:

* not always obvious there is more data to view
* scrolling around tables is a very bad experience on small screens
* potentially we can save citizens from having to scroll at all if we can get more data in the initial view

**Comment by equivalentideas** [comment]
For very small screens we could use [TableSaw](https://github.com/filamentgroup/tablesaw), potentially in the [Column Toggle mode](http://filamentgroup.github.io/tablesaw/demo/toggle.html), which could make the table very readable on small screens.

For mid sized screens we could adjust the max-width of columns to pack more into this view.

I think these steps plus #588 are a good start.

**Comment by mlandauer** [comment]
What's the reason for not trying to use TableSaw on all screen sizes for simplicity?

**Comment by equivalentideas** [comment]
Sorry that's a bit confusing, I meant that TableSaw changes the table for small screens, but it leaves widescreen tables alone—so it's only helping us there. Unless we use some of the extra features like being able to toggle columns, but I'm not so sure about that now, it could make it less clear what columns are present.

**Comment by equivalentideas** [comment]
closed by https://github.com/openaustralia/morph/commit/b6c322228f485c73b397dc1503040578679524f0
