### ISSUE TITLE
Automated cache cleanup of compiled docker images

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#407]
We should probably have some fixed disk space allocation for the compiled docker images. If they go over that allocation we clear out the ones that were used the longest time ago.

This involves tracking the docker image id used in each run

**Comment by mlandauer** [comment]
Let's see if we can get away with not implementing this for the "Make buildpacks the default" milestone

**Comment by mlandauer** [comment]
First stage of this is done. For each run it records the id of the image that was used to create the container.

Another approach (which I now think is better) is to store the time of last usage on an image as metadata on the container. Then, cleanup can happen without knowing anything about runs.

**Comment by henare** [comment]
>Another approach (which I now think is better) is to store the time of last usage on an image as metadata on the ~~container~~ image.

To do this we could add a last used label to the images as they're instantiated as part of the `Morph::DockerRunner.compile_and_start_run` method.

**Comment by henare** [comment]
I've spent a bit of time researching and testing how we can label the time of last usage of Docker images. The bad news is that Docker container/image labels are currently immutable; you can only set them on creation.

There's a [proposal to change this](https://github.com/docker/docker/issues/15496) but it looks like it's a way off so we can't rely on that. This means we need to continue to maintain this information in a system external from Docker, which is definitely not ideal.

Since we're supposedly already doing this in 26f6199 and we've been occasionally cleaning up images over 1 month old, the question is, why is the size of Docker images on morph.io so bloody huge?

Why are there [so many images](https://morph.io/admin/images) that don't have associated runs, and therefore never get cleaned up?

**Comment by henare** [comment]
Arrg, it looks like someone developed the exact feature we need but it was rejected :hurtrealbad: https://github.com/docker/docker/pull/13621

**Comment by henare** [comment]
Cleaning up stopped containers and their images on #945 recovered over 55% of the server's disk space. The tasks to do that have now been wrapped up into a weekly cronjob to try and keep things tidy. While it's not as neat as we might have like, it seems to be doing the job we need for the moment.
