### ISSUE TITLE
Add search over people

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#507]
By handle / name. Related to #103

**Comment by equivalentideas** [comment]
@mlandauer are you free this arvo for a real quick chat in slack about this to see if I'm on the right track with this? I'm not sure if I'm thinking in too small iterations.

Story: As a user, when I want to find a person I know on morph, I want to see them in the results when I search their name.

*Louise searches Longair using the header search form looking for Mark Longair.*

How does Louise distinguish between scrapers and people in the results?

I think on the results page we have a big search form with the term entered, so the person can quickly iterate through searches. This is a familiar pattern from places like [github](https://github.com/search?utf8=%E2%9C%93&q=testing), [google](https://www.google.com.au/search?q=testing), [stackoverflow](http://stackoverflow.com/search?q=testing) etc.

Here's a few rough ideas for consideration for how we incorporate 'people' into the results:

1. **People and Scrapers both appear in the same list of results sorted by relevance** 
![2015-04-21 13 33 52](https://cloud.githubusercontent.com/assets/1239550/7245332/9f212ca4-e82c-11e4-9869-d58a54bd7dea.jpg)
2. **People are Scrapers are in separate lists on the page**
![2015-04-21 13 33 43](https://cloud.githubusercontent.com/assets/1239550/7245330/9d0baa66-e82c-11e4-9213-fdfddc1030fa.jpg)
Similar to [They Vote For You](https://theyvoteforyou.org.au/search?utf8=%E2%9C%93&query=Bishop).
3. **Results for Scrapers and people have their own separate pages/tab panes**
![2015-04-21 13 33 30](https://cloud.githubusercontent.com/assets/1239550/7245325/796637d4-e82c-11e4-9d9a-cdf0c238b6ae.jpg)

I think the 3rd approach, Results for Scrapers and people have their own pages/tab panes, will be clearest of these approaches for someone looking for people and will keep the results clear for people searching for scrapers and data. It's also similar to github's approach to search.

Approach 1 with the single list makes navigation simple and, if the results are good, could make scanning and finding what you're after very quick. If there's lots of similarly relevant results it could get really messy for people trying to scan through different types of information. Also if you're looking for just scrapers, or just people, there are lots of unhelpful results.

I think Approach 2 is confusing as you're not sure if there are more results below if the first list is very long.

## Displaying people/organisation items

In the results for people I think we prioritise identifying information, rather than information about their morph activity. So for people: *full name*, *image*, *user name*, *organisations*, above *number of scrapers*, amount of *data collected*. For organisations: *full name*, *image*, *user name*, *number of members* (maybe member images?), above number of scrapers etc.

I think for the first iteration we use the current display of [people in lists](https://morph.io/users?page=7). Further iterations can add more distinction between people and organisations if necessary, but I think the first important question is just how we get these results lists on the page in a way that is useful for all users.

**Comment by equivalentideas** [comment]
Notes from chat with @mlandauer .

We're gonna prototype the idea the sketch 3.

We going to try the label "Users" for the people/orgs tab, to [follow Github](https://github.com/search?utf8=%E2%9C%93&q=OpenAustralia+Foundation&type=Users&ref=searchresults) and for simplicity.

**Comment by equivalentideas** [comment]
I just pushed a prototype of the 'tabbed' search navigation to branch [`user_search_prototype`](https://github.com/openaustralia/morph/tree/user_search_prototype)

Pretty rough but here's the vibe. The 'scrapers' tab doesn't work, I just hid through results for now.

![screen shot 2015-04-21 at 5 21 00 pm](https://cloud.githubusercontent.com/assets/1239550/7247258/ff5a0262-e84a-11e4-9c6f-5e9a16581dc8.png)

**Comment by equivalentideas** [comment]
Do you think this is headed in the right direction @mlandauer ?

I'm not sure about the heading, maybe just 'Search' and the tabs make it clear what your searching?

**Comment by mlandauer** [comment]
@equivalentideas looking good to me. I see what you're saying about the heading. I think just Search would be fine.

Keep going. Maybe flesh out what info needs to be shown for the users and scrapers here?

**Comment by equivalentideas** [comment]
> looking good to me. I see what you're saying about the heading. I think just Search would be fine.

Cool it’ll strip that back.

> Keep going. Maybe flesh out what info needs to be shown for the users and scrapers here?

Ok cool. I kinda think we should leave scrapers as they are in this iteration as it feels like a separate issue?

Here's what I was thinking about displaying user info above:

> In the results for people I think we prioritise identifying information, rather than information about their morph activity. So for people: full name, image, user name, organisations, above number of scrapers, amount of data collected. For organisations: full name, image, user name, number of members (maybe member images?), above number of scrapers etc.

> I think for the first iteration we use the current display of people in lists. Further iterations can add more distinction between people and organisations if necessary, but I think the first important question is just how we get these results lists on the page in a way that is useful for all users.

I'll move onto that now.

**Comment by mlandauer** [comment]
Sorry I'm not clear. Are you saying you do or don't want to change the way users are displayed in this iteration?

**Comment by equivalentideas** [comment]
Sorry we should have cleared that up :)

I was originally thinking that felt like an additional iteration—and thinking more about it, maybe I should have a go at implementing the user search as above. The only bit that feels tricky is setting up the indexing of users and then adding the routes for type=Users and type=Scrapers .

Or I could leave that to you and move on to the display of users as part of this iteration.

What do you think @mlandauer ?

**Comment by mlandauer** [comment]
@equivalentideas if you think you can do it, go for it. For the urls with "type=users" you simply pass those as parameters to an existing route. So, the url would be something like `search_path(type: "users")`. In the controller for the search action, `@type = params[:type]` and then you can use `@type` in the view to decide which tab to show. Does that vaguely make sense?

**Comment by equivalentideas** [comment]
> Does that vaguely make sense?

@mlandauer it does :rocket: here I go.
