### ISSUE TITLE
Are installation steps in the wrong order?

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#541]
Following the installation step by step, I ran `bundle exec dotenv rake app:update_docker_image` and got:

```
rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'scraping_development'Run `$ bin/rake db:create db:migrate` to create your database
```

I then looked at the next step in the installation guide `bundle exec dotenv rake db:setup`, so I tried running that instead of the suggested `db:create db:migrate` from the error.

Running `bundle exec dotenv rake app:update_docker_image` again, I now passed the database error and instead received:

```
rake aborted!
Errno::ENOENT: No such file or directory - docker
```

which seems unrelated to the database stuff.

Am I right that `bundle exec dotenv rake db:setup` needs to be run before `bundle exec dotenv rake app:update_docker_image`? If so we should swap these steps in the readme.

**Comment by mlandauer** [comment]
@equivalentideas it does sound like the order of those two steps is wrong. With the second problem, that's because it's assuming you have a docker client locally installed which you don't.

You could either:
* Install a docker client locally (there's a build for OS X) and point it at your docker server running on the VM or
* ssh into the vm and run the docker commands to update the docker images

A better solution would be for me to update that rake task so it uses the docker api which is now actually possible.

**Comment by equivalentideas** [comment]
Ok cool, I'll switch round those steps.

I'll try the local docker install.
