### ISSUE TITLE
add column count to table stats

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/morph#590]
Above a scraper’s data table it says 'rows 10 / 940 (320 KB)'. Adding the column count (rows 10 / 940 , 7 columns, 320 KB) gives:

* interesting information about how much data the scraper is collection
* another hint that the table is wider than you may be seeing

**Comment by mlandauer** [comment]
I think the number of columns is much better told to the user by seeing the columns on the table. I think adding an extra number makes the other information less useful because it makes it harder to read.

The fact that we're not showing clearly when there are other tables is a separate issue.

We show the number of rows and database size specifically because it isn't obvious from the table view.

So, I'm closing this if you're cool with that.

**Comment by equivalentideas** [comment]
For me the key question 'does the citizen want to know how many columns are here?'

If they do, counting the columns isn't a great experience if there are a lot.

**Comment by mlandauer** [comment]
The answer is no. You want to know what the columns are. e.g. "Description", "Date"

**Comment by equivalentideas** [comment]
cool :+1:
