### ISSUE TITLE
Search for Santos scraper doesn't work

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#613]
Over lunch I was looking for @equivalentideas' Santos scraper but the search didn't find it: https://morph.io/search?utf8=%E2%9C%93&q=santos

**Comment by mlandauer** [comment]
Curious. https://morph.io/search?utf8=%E2%9C%93&q=santos_news_announcements returns a result. So, the index is getting updated but that search term isn't picking up luke's scraper. Must be a stemming (or some such) thing. Time to delve into elasticsearch a little more.

**Comment by henare** [comment]
What I discovered on Friday is that ElasticSearch only searches full words. By default it considers a string joined by underscores as a single word, e.g. `a_repo_name`.

SearchKick has some built in configuration that allows you to search [partial matches](https://github.com/ankane/searchkick#partial-matches) however it seems to bugger up highlighting.

To solve this properly I think we need to modify the ElasticSearch tokenizer configuration to split up strings that are joined by underscores instead of treating them as a single word. I haven't worked out how to do that yet but it's clearly possible - [GitHub does it](https://github.com/search?utf8=%E2%9C%93&q=santos+user%3Aequivalentideas&type=Repositories&ref=searchresults).

**Comment by mlandauer** [comment]
Would setting the analyzer in searchkick do the trick? https://github.com/ankane/searchkick/blob/master/lib/searchkick/index.rb#L209

**Comment by henare** [comment]
None of those analyzers will do the trick AFAICT so I think we need to make our own.

**Comment by mlandauer** [comment]
I've just done the simple thing for the time being which as @henare mentioned earlier in the thread makes the highlighting work a little surprisingly. I don't think it's a massive deal for the time being as the most important thing is that it returns good results.

However, it would be nice to fix this properly so that at least in the case of indexing `full_name` it tokenises on non-alphanumeric and also handles camelcase.
