### ISSUE TITLE
Currently running scrapers that are errored are not listed as errored

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#728]
There's a PA scraper that has been erroring for ages and ages and I just noticed it was listed as not errored. It appears it's not listed as errored because it's currently running (and stuck running but that's another issue).

If the last run errored and a scraper is running it should still show in lists as errored I think.

**Comment by henare** [comment]
I discovered this problem because my email alert said "19 scrapers you are watching are working. These 2 have a problem:" but that's not the whole story - I'm watching many more. It's just they were "running". Is this a separate issue?

**Comment by mlandauer** [comment]
I've come round to thinking that it's more important to make the email
alerts relevant and that's why i decided to change it so that it only shows
you about things that have finished running in the last 24 hours whether
they were run automatically or not.

For instance, in this morning's alert only something like 2 scrapers
errored but only something like 20 scrapers ran which is a sure sign that
something isn't right.

The whole issue with scrapers getting stuck in the "running" state is a
problem with morph.io and I don't think we should be hacking our way around
it in the email alerts.

The email alerts should be focusing on issues with peoples' scrapers not in
showing problems with the morph.io platform.

**Comment by mlandauer** [comment]
I think this is fixed now. So, closing. Please reopen if you think it needs more work.
