### ISSUE TITLE
Do we need full and accurate names for credit card charging?

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#823]
I see we're using the email address for the "name" field in credit card charging. Is this actually going to work with real credit cards?

If not, how should we collect the name?

Do we just collect when users pay?
Do we use their github name as default?

**Comment by henare** [comment]
>I see we're using the email address for the "name" field in credit card charging.

This was not done intentionally, I just followed the Stripe documentation and didn't come across anything about full names.

**Comment by henare** [comment]
It looks like [it's not essential](https://stripe.com/help/declines#how-do-i-decrease-the-likelihood-of-declines) but can help if you start to get declines:

>The influence of other data that you collect, like the address or name, varies by card brand. For example, only American Express consider the customer’s name.

However we do have a problem - our Stripe customers are being created without an email address. This is a bug (fixed in 3889d7002aa17438ecc52bcc50c56e31bb0b5d90).

**Comment by henare** [comment]
It looks like the only integrated way of collecting a name with Stripe Checkout is using [deprecated bits of the API](http://mattarkin.com/how-to-get-billing-and-shipping-address-data-from-stripe-checkout/). So my take is that they're really pushing people to not bother.

Since we've sorted out the bug with passing an email address properly to Stripe I'm going to close this. Reopen if you disagree or if declines become a problem.

**Comment by mlandauer** [comment]
@henare thanks for looking into this. If we don't have to collect names all the better. The easier we can make it for people the better.
