### ISSUE TITLE
Update wording of plans

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#839]
Because right now we just have "stand-in" names.

From #812 - Possible random ideas for what the levels could be called:
* Open source Supporter, Supporter, Supporter Plus, Priority Supporter
* Micro, Small, Medium, Large
* Names of transformers
* Synonyms of morph
* Names of animated characters that hang out with morph
* Drinks
* Farm animals (to go with the sheep on the landing page?)
* Different kinds of machinery (Tractor, Truck, etc..)
* Bronze, Silver, Gold, Platinum, Unobtanium ($9,999 / month)
* CSV, HTML, PDF
* Free, Hobby, Pro

**Comment by henare** [comment]
Thinking about this over the weekend I've come to realise I really like your idea of becoming the thing ("Become a supporter").

The main other options we have are all ways of labelling an abstract idea. This is useful when you're pricing a segmented internet product because it's intrinsically abstract.

However what we're doing here is different. You're not buying something, you are indeed becoming a supporter of morph.io so it feels right to me.

I've given this a go on [a branch](https://github.com/openaustralia/morph/compare/plan-names) with "Supporter", "Hero", and "Champion". These other words also feel like they fit the fun language of morph.io and the words we naturally use amongst ourselves to describe the people that use and support morph.io.

A few other things fall into place too, like the wording of the "signup" buttons:

![selection_001](https://cloud.githubusercontent.com/assets/48945/8640804/8df36b9c-2948-11e5-9f41-f40469abcd90.png)

**Comment by mlandauer** [comment]
I like heaps

**Comment by mlandauer** [comment]
How about "Partner" instead of "Champion"? Convey a little "professionalism" for the highest plan that gives you priority support?

**Comment by mlandauer** [comment]
One strong reason not to do that is the language is quite different from the others. It sort of highlights even more that the top run is very different. Would this possibly make people less likely to move from middle level to highest level?

**Comment by henare** [comment]
>How about "Partner" instead of "Champion"? Convey a little "professionalism" for the highest plan that gives you priority support?

That's brilliant - it also suggests you contribute so much that you have a shared stake in the project (which you indeed do have).

>One strong reason not to do that is the language is quite different from the others. It sort of highlights even more that the top run is very different. Would this possibly make people less likely to move from middle level to highest level?

That's worth thinking about.

At the prices we've put in currently the highest level is 6 times more of a commitment than standard. Realistically I think only organisations would consider that.

**Comment by henare** [comment]
Maybe "Partner" is too bold for just now (we could save it for when we allow orgs to be supporters?).

Instead we could go for the more common and very direct "Pro". I thought of this again because I thought it would look good on peoples' profiles, i.e. you're a pro.

**Comment by mlandauer** [comment]
Not super-keen on the term "Pro" because I think the way it tends to be succesful on sites like flickr and linkedin is that it can be an aspirational term. We're actually pricing it at a level where it really will only be bigger professional users that use it and they will get less out of being called "Pro" than something like "Partner" IMHO

**Comment by henare** [comment]
Let's go with "Partner" and see how we like it then.
