### ISSUE TITLE
A different icon for entry level

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#843]
Kat suggested a rose much like the emoji. I like that idea.

**Comment by henare** [comment]
+1 for changing what we currently have - it feels a bit World AIDS Day right now :)

**Comment by henare** [comment]
Since we're now calling the basic level simply "supporter" I thought of just a couple figure, side-by-side i.e. standing with us.

I found this on NounProject:

![selection_001](https://cloud.githubusercontent.com/assets/48945/8642531/bf25eeb8-2968-11e5-858c-2b6a6237fa48.png)

Which I quite like but maybe it's too much?

**Comment by mlandauer** [comment]
Assuming we like the little super-hero cartoon characters, I'll close this.
