### ISSUE TITLE
Call webhook when a scraper finishes running

### ISSUE THREAD

**Issue by tmtmtmtm** [openaustralia/morph#915]
It would be super-useful if I could register a URL that gets automatically called when a scraper finishes running, so that I could automatically fetch the new data over the API.

Ideally this would send as a payload the information that gets displayed in the History (result, records added/removed etc), but even a simple result code would be a good first step.

**Comment by henare** [comment]
In #343 @mlandauer suggests you could just do it in the scraper itself.

**Comment by tmtmtmtm** [comment]
That implies it's _my_ scraper. I'd also like to be able to do this for other people's scrapers too.

**Comment by tmtmtmtm** [comment]
@henare we just discovered another reason why doing it in the scraper itself is problematic. At the point where the external call is made by the scraper, the scraper is (by definition) still running, and thus still has the _prior_ version of the database, as it doesn't get replaced by the new version until after the scraper has finished running (since https://github.com/openaustralia/morph/issues/749#issuecomment-105367462, i.e. this wasn't true when @mlandauer made his initial suggestion that this could just be done in the scraper).

This means that the external service needs to immediately return success, and then sleep for a while before doing its actual work, in order to give the scraper time to finish up, and replace the database (without knowing how long that might actually take). 

However if this were built into Morph itself, then it could be set to only trigger once the new version of the database is available, massively simplifying things. 

Even if it were only possible initially to do this for your own scrapers, with an option similar to the setting of environment variables, this would be massively helpful for us.

**Comment by henare** [comment]
@tmtmtmtm that makes sense. I'd be happy to merge a tested simple implementation of this :+1:

**Comment by chrismytton** [comment]
@henare We're going to have a go at implementing this. Wondered if you had any pointers/tips etc that might help me before I dive into the codebase! Specifically:

- Where's the best place in the code to hook in to add this functionality? Presumably I want to run the webhook after the sqlite db has been copied back out of the container?
- Do you have any thoughts on how this might be configured? @tmtmtmtm suggested that perhaps a "magic" environment variable, e.g. `MORPH_WEBHOOK_URL`, which if set would be the target for the webhook. This approach could be good to get a simple version running because the interface is already there, but might back us into a corner in terms of future flexibility.

Thanks!

**Comment by henare** [comment]
@chrismytton that's awesome! :sparkles: 

>Where's the best place in the code to hook in to add this functionality? Presumably I want to run the webhook after the sqlite db has been copied back out of the container?

I'll walk through the process of running a scraper that I just traced back through the code:

* A scraper is queued by calling [the `queue!` method](https://github.com/openaustralia/morph/blob/64d2b761a73124d34b939099daa30ddfd8b1f9f6/app/models/scraper.rb#L252-L259) on the `Scraper` model
* This creates [a new associated `Run`](https://github.com/openaustralia/morph/blob/64d2b761a73124d34b939099daa30ddfd8b1f9f6/app/models/run.rb)
* Which is used by [the `RunWorker`](https://github.com/openaustralia/morph/blob/64d2b761a73124d34b939099daa30ddfd8b1f9f6/app/workers/run_worker.rb) to create an instance of `Morph::Runner` for that run and call the `synch_and_go!` method
* Which eventually [ends up in the `attach_to_run_and_finish` method](https://github.com/openaustralia/morph/blob/64d2b761a73124d34b939099daa30ddfd8b1f9f6/lib/morph/runner.rb#L97-L142)

So the simple version would be to just run the webhook stuff at the end of that method...but that doesn't smell like the right place to me. Then again I haven't looked at it very hard so that's something you'll need to judge when you implement it :smiley: 

>Do you have any thoughts on how this might be configured? @tmtmtmtm suggested that perhaps a "magic" environment variable, e.g. MORPH_WEBHOOK_URL, which if set would be the target for the webhook. This approach could be good to get a simple version running because the interface is already there, but might back us into a corner in terms of future flexibility.

Environment variables are something used _in_ the scraper itself and given the expectation that these webhooks are only used by _morph.io_ and not the scraper I think that could be confusing (i.e. "why are these exposed to the scraper when they're only ever used by morph.io?").

The first pass could be to add another section to the scraper settings for these (which has the side effect of more complexity on that screen but maybe that's OK?).

---

A couple of other things:

Sadly the codebase doesn't have much in the way of tests. If you could add any as you go that would be a huge help. Not only does it help the reliability but also helps us review and merge the pull request.

We're quite fond of opening early WIP pull requests so if you are please feel free to do so.
