### ISSUE TITLE
User menu doesn't show up on screens around tablet size

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#918]
It's between desktop and mobile:

![selection_001](https://cloud.githubusercontent.com/assets/48945/10012343/806430c6-614a-11e5-8300-07a1b2532ef9.png)

**Comment by EkaterinaSemenova** [comment]
Hi @henare ,
I believe that #1143 should fix this.

**Comment by equivalentideas** [comment]
Just to be clearer, this issue is about the 'user' section of the menu that shows the user name etc. . And specifically about it when the menu is in the small screen drop down mode.

![screen shot 2017-04-07 at 9 59 56 am](https://cloud.githubusercontent.com/assets/1239550/24780254/378c9eac-1b79-11e7-9858-ff8afff4aa83.png)

For some reason, it doesn't shown up on screens medium width screens—but it is accessible on smaller and wider screens. Here's what that looks like:

![screen shot 2017-04-07 at 9 59 56 am](https://cloud.githubusercontent.com/assets/1239550/24780277/6185deee-1b79-11e7-8bb3-1acfae912952.png)
![screen shot 2017-04-07 at 10 00 09 am](https://cloud.githubusercontent.com/assets/1239550/24780278/618c733a-1b79-11e7-81e7-4bdc8854a09f.png)
![screen shot 2017-04-07 at 10 00 20 am](https://cloud.githubusercontent.com/assets/1239550/24780280/619537d6-1b79-11e7-8a19-f81971c3b229.png)
![screen shot 2017-04-07 at 10 00 30 am](https://cloud.githubusercontent.com/assets/1239550/24780279/618effe2-1b79-11e7-9fe6-4c31f6fdff2b.png)

I wonder if there's a height setting on the menu or something that's hiding it?
