### ISSUE TITLE
Unexpected redirect in scraper

### ISSUE THREAD

**Issue by chrismytton** [openaustralia/morph#931]
I've created a test scraper, [chrismytton/uae-test](https://morph.io/chrismytton/uae-test), which runs a simple `curl` command. When I run it locally it returns a 200 and the expected html, however running it on morph gives a "302 Found". I'm unable to reproduce this anywhere else so I was wondering if this is something you've encountered before?

I have my suspicions that it might be something the ASP.NET server I'm hitting is doing because of the SSL certificate being generated by mitmproxy or something, but I have no evidence to back that up.

**Comment by henare** [comment]
Hey Chris, my guess would also be that it's something to do with mitmproxy.

I think this question would be more suited to the [help forum](https://help.morph.io/) and if there's a change we need to make in morph.io then we can open another issue.

It would be great if you could open a thread on the forum describing what you're trying to do and why you're shelling out instead of using a library like Mechanize.

**Comment by chrismytton** [comment]
@henare Thanks for the quick response!

I wasn't totally clear in my original question, the [chrismytton/uae-test](https://morph.io/chrismytton/uae-test) scraper was just a simple way to demonstrate the problem I was having. The scraper that's actually failing is [chrismytton/united-arab-emirates-federal-national-council](https://morph.io/chrismytton/united-arab-emirates-federal-national-council) which uses phantomjs via poltergeist to do the scraping.

I'll ask a question on the help forum to see if anyone else has a workaround for this issue, then re-raise here if necessary.
