### ISSUE TITLE
Unable to access my profile or scraper or search

### ISSUE THREAD

**Issue by Abbie2020** [openaustralia/morph#943]
From homepage, when I click on my face then My Profile I get "Something went wrong". Same when going to my scraper URL: https://morph.io/Abbie2020/sri_lanka_members_of_parliament or searching for a term from the homepage.

**Comment by IvanGoncharov** [comment]
@Abbie2020 I have exactly same problems, that mean it on server side.

**Comment by qqphot** [comment]
Same here.

**Comment by henare** [comment]
Hi everyone, thanks for reporting this problem. We've been running very low on storage lately and this problem has happened because we've finally hit full disks, again.

I'm trying to fix it now and I'll update this ticket as I go.

We can't afford to wastefully horizontally upgrade the server again either so #407 needs to be fixed stop this happening again almost immediately.

**Comment by henare** [comment]
I've cleared out enough disk space, via the problem identified in #944, and things are working again. There's around 150 jobs in the queue right now so it could take a little while for your scrapers to be run.

**Comment by Abbie2020** [comment]
Thanks :smiley:
