### ISSUE TITLE
Morph.io is down

### ISSUE THREAD

**Issue by IvanGoncharov** [openaustralia/morph#980]
Website is down for at least half a day.
http://www.downforeveryoneorjustme.com/morph.io

**Comment by henare** [comment]
@IvanGoncharov thanks for the notification :+1: I'm investigating now.

New Relic says the outage started 9 hours ago :disappointed:

**Comment by henare** [comment]
The server console had this:

![lish web console - mozilla firefox_001](https://cloud.githubusercontent.com/assets/48945/13968491/16f21308-f0d1-11e5-893e-12b8beace504.png)

Which looks like a pretty low level kernel problem. Strange that it mentions Python and PhantomJS (most likely a scraper written in the former using the latter).

I rebooted the server, the disks were checked and it's looking good. Since there was such a long outage the queue has almost 400 scrapers in it so that will take a little time to clear.

There's not a whole lot more investigation I can think to do at this stage so we'll keep an eye on it and see if it happens again.

**Comment by IvanGoncharov** [comment]
@henare Thanks.
> Strange that it mentions Python and PhantomJS (most likely a scraper written in the former using the latter).

The long time ago I worked as Linux kernel developer.
This log looks like a deadlock in kernel between two cores.
`Python` and `PhantomJS` mentioned here as userspace processes that executed before these cores switched into kernel space.
Big chance that it haven had anything to do them and switch was made by a timer in order to do process scheduling. 

> There's not a whole lot more investigation I can think to do at this stage so we'll keep an eye on it and see if it happens again.

The only thing you can do in such situations is to use magic SysRq:
https://en.wikipedia.org/wiki/Magic_SysRq_key

**Comment by henare** [comment]
@IvanGoncharov thanks for that :sparkles:

I'm guessing this is typically hardware related and since morph.io is hosted on Linode, it's some interaction between the kernel and the hypervisor? I seem to remember having to debug some kernel issue similar to this in the past (just not on morph.io).

If you can think of anything we should do to mitigate this, or any other action to take, I'd be happy to hear it.

**Comment by IvanGoncharov** [comment]
@henare Just use some monitoring service.
Which ping your service and send SMS or email if it doesn't respond.
It's a bad situation where you find out that your server stuck from Github issue.

**Comment by IvanGoncharov** [comment]
@henare I really like your service and appreciate work that you do.
Problem is that I rely a lot on it for my project and in last half a year I experience a lot of problems with it.
I understand that it open source project and I don't have any rights to demand anything from you.
But you can try to offload some task to a community, just try to engage users more.

**Comment by henare** [comment]
>Just use some monitoring service.
>Which ping your service and send SMS or email if it doesn't respond.
>It's a bad situation where you find out that your server stuck from Github issue.

@IvanGoncharov we already monitor morph.io. This outage started at 23:00 and was resolved when I woke up at 08:00 the next day after seeing the outage notifications.

>I really like your service and appreciate work that you do.
>Problem is that I rely a lot on it for my project and in last half a year I experience a lot of problems with it.
>I understand that it open source project and I don't have any rights to demand anything from you.
>But you can try to offload some task to a community, just try to engage users more.

If it's important to you have you thought about becoming a supporter? https://morph.io/supporters/new

If you'd like to help out by engaging users more that would also be an excellent contribution to make.

**Comment by IvanGoncharov** [comment]
@henare Subscribed for 14$/month.
Can't donate more since ~80-90% of my time I dedicate to open-source projects.
Love to help with code contribution but don't have any Ruby knowledge.
Can help with Node.js if you have tasks related to it.

> If you'd like to help out by engaging users more that would also be an excellent contribution to make.

Why you can't add a banner on the main page of morph.io asking people to contribute PRs?
It's a very logical step to take, especially since you already have `entry level` tasks [marked](https://github.com/openaustralia/morph/issues?q=is%3Aissue+is%3Aopen+label%3A%22easy+fix%22).

**Comment by henare** [comment]
>@henare Subscribed for 14$/month.
>Can't donate more since ~80-90% of my time I dedicate to open-source projects.

Thank you, it's much appreciated! :sparkles: 

>Why you can't add a banner on the main page of morph.io asking people to contribute PRs?
>It's a very logical step to take, especially since you already have entry level tasks marked.

I don't see why not, can you open an issue for that? It's a common pattern to have a little ribbon in the top-right of the page, maybe we could do that?
