### ISSUE TITLE
Failed buildpack compilation gets cached and scraper can never run

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#987]
If a buildpack compilation fails from #986 then that compilation is cached and the scraper forever tries to use it.

This is what was happening in #985 because the image created with the default scraperwiki libraries was cached and the install had failed during the compilation of that image. Arrrg! :fire: 

Fixing this is a nightmare. The only way to reliably do it is to remove every image from the server so it's rebuilt correctly.

**Comment by mlandauer** [comment]
When compiles fail at the morph level they don't get cached. The reason this issue is happening is actually caused by an underlying issue which is the failure of the python buildpack to signal its failure up the chain.

So, this issue is fixed if we fix #589.

But in reality the issue as it's stated in this ticket isn't actually an issue at all. Does that even vaguely make sense?
